v=load('v1.mat');
x=v.val(1,:);
        %% FT of x
N=length(x);
T=10;
fs=N/T;
t=0:1/fs:T-1/fs;
f=-fs/2:fs/N:fs/2-fs/N;
X=fftshift(fft(x));
        %% Forming Fourier Transfrom of delta theta alpha beta gamma
f_dn=find(abs(f)<0.5 | abs(f)>4);
f_tn=find(abs(f)<4   | abs(f)>8);
f_an=find(abs(f)<8   | abs(f)>13);
f_bn=find(abs(f)<13  | abs(f)>35);
f_gn=find(abs(f)<35);
D=X;
T=X;
A=X;
B=X;
G=X;
D(f_dn)=0;
T(f_tn)=0;
A(f_an)=0;
B(f_bn)=0;
G(f_gn)=0;
        %% Converting FTs to time domain signal
D=ifftshift(D);
T=ifftshift(T);
A=ifftshift(A);
B=ifftshift(B);
G=ifftshift(G);
delta=ifft(D);
theta=ifft(T);
alpha=ifft(A);
beta=ifft(B);
gamma=ifft(G);
        %% Plotting the time-domain signals of delta theta alpha beta gamma
figure(1);
subplot(5,1,1);
plot(t,gamma);
xlabel('t (s)');
ylabel('Amplitude');
title('Gamma');
subplot(5,1,2);
plot(t,beta);
xlabel('t (s)');
ylabel('Amplitude');
title('Beta');
subplot(5,1,3);
plot(t,alpha);
xlabel('t (s)');
ylabel('Amplitude');
title('Alpha');
subplot(5,1,4);
plot(t,theta);
xlabel('t (s)');
ylabel('Amplitude');
title('Theta');
subplot(5,1,5);
plot(t,delta);
xlabel('t (s)');
ylabel('Amplitude');
title('Delta');